export const SET_TIMER_STATE = "SET_TIMER_STATE";
export const SET_START_TIME = 'SET_START_TIME';
export const SET_START_LAP_TIME = 'SET_START_LAP_TIME';
export const SET_MAIN_TIMER = 'SET_MAIN_TIMER';
export const SET_CALCULATED_TIME = 'SET_CALCULATED_TIME';
export const SET_AMOUNT_OF_CALCULATED_TIME = 'SET_AMOUNT_OF_CALCULATED_TIME';
export const SET_BUTTON_BLOCK = 'SET_BUTTON_BLOCK';
export const SET_INTERVAL_HISTORY = 'SET_INTERVAL_HISTORY';